name: Backend and Frontend Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: 19
        working-directory: backend

      - name: Run backend lint and test
        run: |
          npm ci
          npm run lint
          npm run test:coverage
        working-directory: backend

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: 19
        working-directory: frontend

      - name: Run frontend lint
        run: |
          npm ci
          npm run lint
        working-directory: frontend