name: Backend and Frontend Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
<<<<<<< HEAD
      - master
=======
      - '**'
>>>>>>> b5b77f20c382fadc8c91cb4f72f319c5dbad8a0a

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: Install dependencies and run backend tests
        run: |
          cd backend
          npm ci
          npm run lint
          npx zenstack generate
          npm run test:coverage

      - name: Install dependencies and run frontend tests
        run: |
          cd frontend
          npm ci
          npm run lint